name: Convert and Deploy Notebooks

on:
  push:
    branches:
      - main

jobs:
  convert-and-deploy:
    uses: advafaeian/blog-shared-workflow/.github/workflows/convert-and-copy.yml@main
    secrets:
      TARGET_REPO_TOKEN: ${{ secrets.BLOG_WORKFLOW_ACCESS_TOKEN }}

